#pragma once

#include "cmsis_os.h"

extern osThreadId_t defaultTaskHandle;
extern osThreadId_t transmitMessagesTaskHandle;
extern osThreadId_t parseMessagesTaskHandle;
extern osThreadId_t executeCommandsTaskHandle;
extern osThreadId_t checkConnectionTaskHandle;
extern osMessageQueueId_t receivedBytesQueueHandle;
extern osMessageQueueId_t transmitMessagesQueueHandle;
extern osMessageQueueId_t heartbeatsQueueHandle;
extern osMessageQueueId_t commandsQueueHandle;
extern osTimerId_t sendHeartbeatsTimerHandle;
extern osTimerId_t reportStatusTimerHandle;
extern osSemaphoreId_t usbOccupationBinarySemHandle;
